- name: Test play
  hosts: localhost
  tasks:
    - name: Log hostvars
      ansible.builtin.debug:
        var: hostvars

    - name: Log hello world
      ansible.builtin.debug:
        msg: "Hello world"

    - name: Log facts
      ansible.builtin.debug:
        var: ansible_facts

- name: Test Vagrant host connection
  hosts: vagrant
  tasks:
    - name: Log facts
      ansible.builtin.debug:
        var: ansible_facts
